# Generated by Django 2.2.2 on 2019-06-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaillist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
