# Generated by Django 2.2.2 on 2019-06-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaillist', '0002_auto_20190623_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Email Holder's Name"),
        ),
    ]
